[package]
name    = "mat-frame-art"
version = "0.1.0"
edition = "2021"

[dependencies]
clap  = { version = "4", features = ["derive"] }
image = "0.25"
imageproc = "0.25"
usvg  = "0.45"
resvg = "0.45"
